name: news_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  intl: ^0.19.0
  http: ^1.2.0
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  go_router: ^13.2.2
  sliver_tools: ^0.2.12
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  smooth_page_indicator: ^1.1.0
  animated_text_kit: ^4.2.2
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  adaptive_theme: ^3.6.0
  shared_preferences: ^2.2.2
  country_code_picker: ^3.0.0
  rive: ^0.13.1
  flutter_launcher_icons: ^0.13.1
  bottom_navy_bar: ^6.0.0
  liquid_swipe: ^3.1.0
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF2950"
  remove_alpha_ios: true


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Black.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
    - family: Abys
      fonts:
        - asset: lib/assets/fonts/Abys-Regular.otf
    - family: Blackness
      fonts:
        - asset: lib/assets/fonts/Blackness.ttf
        
       